default:
  sebms:
    driver: !expr RPostgres::Postgres() 
    server: 'localhost'
    dbuser: !expr Sys.getenv("DBUSER")
    dbpass: !expr Sys.getenv("DBPASS")  
    port: !expr Sys.getenv("DBPORT")
    database: !expr Sys.getenv("DBNAME")

